# use java support
language: java
jdk:
  - openjdk11

# run in container
sudo: false

# use linux as operating system
os:
  - linux

# run maven build
script:
  - ./gradlew clean build

cache:
  directories:
    - $HOME/.gradle/caches/

# Deploy snapshots on every commit made to master branch
# Deploy releases on every tag push
deploy:
  - provider: script
    script: ./gradlew publish -PrepositoryUrl=$url/public-snapshots/ -PrepositoryUsername=$username -PrepositoryPassword=$password
    skip_cleanup: true
    on:
      branch: master

  - provider: script
    script: ./gradlew publish -PrepositoryUrl=$url/releases/ -PrepositoryUsername=$username -PrepositoryPassword=$password
    skip_cleanup: true
    on:
      tags: true